
appname: apache
environment: dev
replicaCount: 1
image:
  repository: fontanillamiguel/apache
  tag: v0.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetport: 8080
  nodeport: 31228
  servicename: httpd-service

pvc:
  accessmodes: ReadWriteOnce
  request: 1Gi
  claimname: myhttpdclaim

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ok"
    #nginx.ingress.kubernetes.io/auth-secret: "basic-auth"
    #nginx.ingress.kubernetes.io/auth-type: "basic"
    #nginx.ingress.kubernetes.io/rewrite-target: /
  host: mywebserver.dev.kubesandclouds.com
  path: /

resources: 
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

serviceAccount:
  create: false

nodeSelector: {}

tolerations: []

affinity: {}
