apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: nginx-ingress
  chart:
    git: git@github.com:mifonpe/helmflux
    path: nginx-ingress
    ref: master
